version: "3"

services:
  node:
    image: "node:18.0.0"
    volumes:
      - .:/src/medbox-web
    working_dir: /src/medbox-web
    command: >
      sh -c "yarn &&
      yarn build &&
      yarn start"
    ports:
      - 3000:3000

volumes:
  medbox-client:
    external: true
